---
- hosts: all
  tasks:
    - name: Print some debug information 
   vars: 
    msg: |
     Morpheus Variables ("morpheus")

     --------------------------------

     {{ morpheus | to_nice_json }}
   debug: 
    msg: "{{ msg.split('\n') }}"    
   tags: debug_info
